# Použite oficiálny Node.js image
FROM node:14

# Nastavte pracovný adresár v kontajneri na 'project-root'
WORKDIR /project-root

# Kopírujte package.json a package-lock.json
COPY package*.json ./

# Inštalujte NPM závislosti
RUN npm install
# RUN npm rebuild sqlite3

# Kopírujte všetky zdrojové súbory projektu do kontajnera
COPY . .

# Váš projekt beží na porte (predpokladám 3000)
EXPOSE 3000

# Spustenie aplikácie
CMD ["npm", "start"]
